import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Blog and Todos",
    default: "Blog and Todos",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="flex min-h-screen flex-col items-center justify-center bg-gray-800 font-mono text-white">
        {" "}
        <main className="flex w-full flex-1 flex-col items-center justify-center">
          {children}
        </main>
        <footer className="flex h-6 w-full items-center justify-center text-sm text-gray-500">
          @Udemy 2021
        </footer>
      </body>
    </html>
  );
}
